apiVersion: v1
kind: Service
metadata:
  name: shopcarts
  labels:
    app: shopcarts
spec:
  selector:
    app: shopcarts
  type: ClusterIP
  internalTrafficPolicy: Cluster
  ports:
    - name: 8080-tcp
      protocol: TCP
      port: 8080
      targetPort: 8080